name: Vercel Deploy

on:
  push:
    branches:
      - main # ou a branch que deseja monitorar para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # ou versão adequada do Node.js

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build #npm run build # ou comando para build do seu projeto

      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
